/*
 ################################################################
 Copyright (c) 2010 Amazon.com, Inc., and its Affiliates.
 All rights reserved.
 Not to be reused without permission
 ################################################################
*/
(function(){var p=function(j){(function(a){typeof amzn=="undefined"&&(amzn={});if(typeof amzn.cs=="undefined")amzn.cs={};if(typeof amzn.cs.log=="undefined")amzn.cs.log={};amzn.cs.log.LOG_EVENT_NAME="amzn.cs.log.LogEvent";amzn.cs.log._loggersByName={};amzn.cs.log._levels={DEBUG:1,LOG:2,INFO:3,WARN:4,ERROR:5,OFF:6};amzn.cs.log._throw=function(a){throw"[amzn.cs.log] "+a;};amzn.cs.log._Logger=function(a){this._name=a;this._level=amzn.cs.log._levels.DEBUG;this._logCallbacks=[]};amzn.cs.log._Logger.prototype._log=
function(e,c,f){if(c>=this._level){this.prefix&&(typeof this.prefix=="function"?Array.prototype.unshift.call(f,this.prefix()):Array.prototype.unshift.call(f,this.prefix));if(typeof console!=="undefined"){var g;if(typeof console[e]!="undefined")g=console[e];else if(typeof console.log!="undefined")g=console.log;g&&(typeof g.apply=="function"?g.apply(console,f):g(Array.prototype.join.call(f," ")))}for(e=0;e<this._logCallbacks.length;e++)this._logCallbacks[e](f);c={name:this._name,level:c,args:Array.prototype.splice.call(f,
0),time:(new Date).getTime()};a(document).trigger(amzn.cs.log.LOG_EVENT_NAME,[c])}};amzn.cs.log._LogAccumulator=function(e){this._options=a.extend({},e,{maxLogs:100,includeJsErrors:!0});this._lastErrorTime=0;this._logs=[];this._listenForLogs();this._options.includeJsErrors&&this._listenForJsErrors()};amzn.cs.log._LogAccumulator.prototype._pushLogEntry=function(a){this._logs.push(a);this._logs.length>this._options.maxLogs&&this._logs.shift();if(a.level==amzn.cs.log._levels.ERROR)this._lastErrorTime=
(new Date).getTime()};amzn.cs.log._LogAccumulator.prototype._listenForLogs=function(){var e=this;a(document).bind(amzn.cs.log.LOG_EVENT_NAME,function(a,f){e._pushLogEntry(f)})};amzn.cs.log._LogAccumulator.prototype._listenForJsErrors=function(){var a=this;oldOnError=window.onerror;window.onerror=function(c,f,g){a._pushLogEntry({js:!0,level:amzn.cs.log._levels.ERROR,time:(new Date).getTime(),msg:c,url:f,line:g});return oldOnError?oldOnError(c,f,g):!1}};amzn.cs.log.initLogAccumulator=function(a){return amzn.cs.log._accumulator?
!1:(amzn.cs.log._accumulator=new amzn.cs.log._LogAccumulator(a),!0)};amzn.cs.log.getLogAccumulator=function(){return amzn.cs.log._accumulator};amzn.cs.log._LogAccumulator.prototype.hasError=function(){return this._lastErrorTime>=this._logs[0].time};amzn.cs.log._LogAccumulator.prototype.dump=function(){return JSON.stringify(this._logs)};amzn.cs.log.getLogger=function(a){var c=amzn.cs.log._loggersByName[a];typeof c=="undefined"&&(c=new amzn.cs.log._Logger(a),amzn.cs.log._loggersByName[a]=c);return c};
amzn.cs.log.destroyLogger=function(a){delete amzn.cs.log._loggersByName[a]};amzn.cs.log._Logger.prototype.turnOff=function(){this.setLevel("OFF")};amzn.cs.log._Logger.prototype.setLevel=function(a){var c=amzn.cs.log._levels[a.toUpperCase()];typeof c=="undefined"&&amzn.cs.log._throw("unknown level: "+a);this._level=c};amzn.cs.log._Logger.prototype.setPrefix=function(a){this.prefix=a};amzn.cs.log._Logger.prototype.addCallback=function(a){this._logCallbacks.push(a)};amzn.cs.log._Logger.prototype.debug=
function(){this._log("debug",amzn.cs.log._levels.DEBUG,arguments)};amzn.cs.log._Logger.prototype.log=function(){this._log("log",amzn.cs.log._levels.LOG,arguments)};amzn.cs.log._Logger.prototype.info=function(){this._log("info",amzn.cs.log._levels.INFO,arguments)};amzn.cs.log._Logger.prototype.warn=function(){this._log("warn",amzn.cs.log._levels.WARN,arguments)};amzn.cs.log._Logger.prototype.error=function(){this._log("error",amzn.cs.log._levels.ERROR,arguments)}})(j)};window.P&&window.P.AUI_BUILD_DATE?
P.when("jQuery").execute(function(j){p(j);P.register("TelephonyJSLogger",function(){})}):p(window.jQuery)})();
(function(){var p=function(j){var a=window.amzn=window.amzn||{};if(typeof a.cs==="undefined")a.cs={};if(typeof a.cs.log==="undefined")a.cs.log={};if(typeof a.cstel==="undefined")a.cstel={};(function(a){function c(b,a,d,e){e.timeoutCount++;if(e.timeoutCount===g)b.apply(window,arguments);else{var d=d||500,f=(new Date).getTime()+a;e.timerId=window.setTimeout(function(){var a=f-(new Date).getTime();e.earlinesses.push(a);a>=d?c(b,a,d,e):b.apply(window,arguments)},a)}}typeof TelephonyUtil=="undefined"&&
(TelephonyUtil={});TelephonyUtil.Array={indexOf:function(b,a){if(typeof b.indexOf!="undefined")return b.indexOf(a);else{for(var d=b.length,c=0;c<d;c++)if(a===b[c])return c;return-1}},contains:function(b,a){return TelephonyUtil.Array.indexOf(b,a)!=-1}};TelephonyUtil.isIE6=typeof navigator!="undefined"&&/msie|MSIE 6/.test(navigator.userAgent);TelephonyUtil.putInLocalStorage=function(b,a){var d=typeof a;try{d==="object"&&(a=JSON.stringify(a));var c=window.localStorage||{};c.setItem(b,a);c.setItem(b+
"__type__",d)}catch(e){TelephonyUtil.logError("Could not save key "+b+"in localStorage",e)}};TelephonyUtil.getFromLocalStorage=function(b){var a=null,d=null;try{var c=window.localStorage||{},d=c.getItem(b+"__type__"),a=c.getItem(b)}catch(e){TelephonyUtil.logError("Could not get item with key "+b+"in localStorage",e)}if(typeof a==="string"&&d==="object"){b=a;try{a=JSON.parse(b)}catch(f){TelephonyUtil.logError("Could not parse json: "+b,f)}}return a};TelephonyUtil.logError=function(b,a){window.console&&
console.error&&console.error(b,a)};TelephonyUtil.createMapCache=function(b){return new f(b)};var f=function(b){var d=this;this._options=a.extend({sweepTime:6E4,onSweepComplete:function(){}},b);this._map={};this._hasExpired=function(b){return b&&b.expiration<(new Date).getTime()};this._sweep=function(){var b=[],a;for(a in d._map)d._hasExpired(d._map[a])&&b.push(a);for(var c=0;c<b.length;c++)a=b[c],delete d._map[a];d._options.onSweepComplete()};window.setInterval(function(){d._sweep()},d._options.sweepTime);
this.put=function(b,a,c){c&&(a={expiration:(new Date).getTime()+c,value:a},d._map[b]=a)};this.get=function(b){var a=d._map[b];if(a)if(d._hasExpired(a))delete d._map[b];else return a.value}};TelephonyUtil.setTimeout=function(b,a,d){var e={timeoutCount:0,earlinesses:[]};c(b,a,d,e);return e};var g=20,d=/[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}/;TelephonyUtil.sanitizeGUID=function(b){if(typeof b=="string"){var a=b.match(d);if(a)return a[0]}return b};TelephonyUtil.trimXHR=function(b){return!b?
{}:{status:b.status,statusText:b.statusText,responseText:b.responseText,timeout:b.timeout,readyState:b.readyState}};TelephonyUtil.hitch=function(b,a){if(!a)return a;var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments,0),c=d.concat(c);a.apply(b,c)}};TelephonyUtil.validateParamIsNotMissing=function(b,a){if(TelephonyUtil.isParamMissing(a))throw Error('No value provided for parameter "'+b+'", but it is required.');};TelephonyUtil.validateParamIsNotEmpty=
function(b,d){TelephonyUtil.validateParamIsNotMissing(b,d);if(!a.isFunction(d)&&typeof d.length==="number"&&d.length===0)throw Error('An empty value was provided for parameter "'+b+'", but it is required to be non-empty.');};TelephonyUtil.validateParamIsFunction=function(b,a){TelephonyUtil.validateParamIsNotMissing(b,a);if(typeof a!=="function")throw Error('A non-function was provided for paramter "'+b+'", but a function is required. Actual value passed: '+a);};TelephonyUtil.isParamMissing=function(b){return typeof b===
"undefined"||b===null?!0:!1};TelephonyUtil.substituteString=function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b=b.replace("${"+d+"}",a[d]));return b};TelephonyUtil.arrayMove=function(b,a,d){var c=b[a];b.splice(a,1);b.splice(d,0,c)}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.cs=="undefined")a.cs={};if(typeof a.cs.util=="undefined")a.cs.util={};e.fn.amznSafeShow=function(a){a||(a={});var f=typeof a.animate=="undefined"?!0:a.animationEnabled,g=a.durationMs||500,d=a.easingFunction||
"linear";return this.each(function(){var b=e(this);if(f){var a=b.height(),c=b.css("height");b.filter(":hidden").css("height","1px").animate({height:a,width:"show",opacity:"show"},g,d,function(){b.css("height",c)})}else e(b).show()})};e.fn.amznSafeHide=function(a){a||(a={});var f=typeof a.animate=="undefined"?!0:a.animationEnabled,g=a.durationMs||500,d=a.easingFunction||"linear";return this.each(function(){var b=e(this);if(f){var a=b.css("height");b.filter(":visible").animate({height:"1px",width:"hide",
opacity:"hide"},g,d,function(){b.hide().css("height",a)})}else e(b).hide()})}})(j);if(!this.JSON)this.JSON={};(function(){function a(b){return b<10?"0"+b:b}function c(b){d.lastIndex=0;return d.test(b)?'"'+b.replace(d,function(b){var a=i[b];return typeof a==="string"?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function f(a,d){var i,e,g,r,j=b,o,s=d[a];s&&typeof s==="object"&&typeof s.toJSON==="function"&&(s=s.toJSON(a));typeof m==="function"&&(s=m.call(d,a,s));switch(typeof s){case "string":return c(s);
case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);case "object":if(!s)return"null";b+=h;o=[];if(Object.prototype.toString.apply(s)==="[object Array]"){r=s.length;for(i=0;i<r;i+=1)o[i]=f(i,s)||"null";g=o.length===0?"[]":b?"[\n"+b+o.join(",\n"+b)+"\n"+j+"]":"["+o.join(",")+"]";b=j;return g}if(m&&typeof m==="object"){r=m.length;for(i=0;i<r;i+=1)e=m[i],typeof e==="string"&&(g=f(e,s))&&o.push(c(e)+(b?": ":":")+g)}else for(e in s)Object.hasOwnProperty.call(s,
e)&&(g=f(e,s))&&o.push(c(e)+(b?": ":":")+g);g=o.length===0?"{}":b?"{\n"+b+o.join(",\n"+b)+"\n"+j+"}":"{"+o.join(",")+"}";b=j;return g}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};
var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b,h,i={"":"\\b","\t":"\\t","\n":"\\n","":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},m;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,d,c){var i;h=b="";if(typeof c==="number")for(i=0;i<c;i+=1)h+=" ";else typeof c==="string"&&(h=c);if((m=d)&&typeof d!==
"function"&&(typeof d!=="object"||typeof d.length!=="number"))throw Error("JSON.stringify");return f("",{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(b,a){function d(b,h){var c,i,e=b[h];if(e&&typeof e==="object")for(c in e)Object.hasOwnProperty.call(e,c)&&(i=d(e,c),i!==void 0?e[c]=i:delete e[c]);return a.call(b,h,e)}var h;g.lastIndex=0;g.test(b)&&(b=b.replace(g,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return h=eval("("+b+")"),typeof a==="function"?d({"":h},""):h;throw new SyntaxError("JSON.parse");}})();(function(e){typeof a=="undefined"&&(a={});if(typeof a.coraljsonp=="undefined")a.coraljsonp={};var c=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest;navigator.userAgent.indexOf("Trident")!==-1&&(c=!1);a.coraljsonp.queryService=function(f){var f=f||{},d=f.params||
{},b=f.url||"",h=f.onSuccess||function(){},i=f.onError||function(){},m=f.onComplete||function(){},u=f.resultNestedLocation||[],l=f.requiredKeys||[],k=f.operation||"",n=typeof f.isCoral==="undefined"?!0:f.isCoral,j=typeof f.crossDomain=="undefined"?!0:f.crossDomain,r=j&&f.crossDomainXhrEnabled&&c,q=typeof f.timeout==="undefined"?6E3:f.timeout,o=f.logger,f=f.jsonpChannel;o||(o=typeof a!="undefined"&&a.cs&&a.cs.log?a.cs.log.getLogger("coraljsonp"):typeof console!="undefined"&&console.debug&&console.error?
console:{debug:function(){},error:function(){}});j=j&&!r;if(n&&(d.Operation=k,d.ContentType="JSON",j))d.JSONCallBack="?";var s=!1,z=function(b,a,d,h){s=!0;var c=i(b,a,d,h);m();c||(h?o.error("Modelled error. Code:",h):(b=TelephonyUtil.trimXHR(b),o.error("AJAX error. Status:",a," Error:",d," XHR:",b)))},w=b;k&&(w=w+"|"+k);o.debug("Requesting "+w);var x=null,t=a.coraljsonp._registerAjaxCall({log:o,requestDescriptor:w,timeoutMs:q,timeoutHandler:function(){z(x,"timeout","Call to "+w+" timed out after "+
q+" ms");x&&x.abort()}}),y=(new Date).getTime();a.coraljsonp.doh&&(b+="http://www.dooooooooooooooooooooh.com");d={url:b,data:d,cache:!1,dataType:j?"jsonp":"json",jsonp:n?"JSONCallBack":"callback",success:function(d,c){if(!s){a.coraljsonp._markAjaxCallReceived(t);var i=(new Date).getTime()-y;if(!k){var f=b.split(/:\/\/[\w\.:]+/);k=f.length==2?f[1]:b}o.debug("Response for "+k,"("+i+" ms)");d.Error&&d.Error.Code?z(null,null,null,d.Error.Code):(d=a.coraljsonp._drillIntoResult(d,u,l,function(b){z(null,
null,"Missing key: "+b)}),d!==null&&(h(d,c),m()))}},error:function(b,d,h){a.coraljsonp._markAjaxCallReceived(t);z(b,d,h)}};j&&f?(d.iframeName=a.coraljsonp._getChannelIFrameName(f),d.logger=o,a.coraljsonp._jsonpInIFrame(d)):r?x=a.coraljsonp._sendCrossDomainXhr(d):e.ajax(d)};a.coraljsonp._sendCrossDomainXhr=function(a){var d=new XMLHttpRequest,b=a.url,h=a.data||{},c=a.error||function(){},f=a.success||function(){};if(!b)throw"url param required";d.onreadystatechange=function(){if(d.readyState==4)if(d.status!=
200)c(d,"error",d.statusText);else{var b;try{b=JSON.parse(d.responseText)}catch(a){c(d,"parseerror",a);return}f(b,d.statusText,d)}};d.open("POST",b);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.send(e.param(h))};a.coraljsonp.cleanupChannel=function(c){var d=a.cs.log.getLogger("coraljsonp");try{var b=a.coraljsonp._getChannelIFrameName(c);e('iframe[name="'+b+'"]').remove();delete window.frames[b]}catch(h){d.error("Error cleaning up channel",c,h)}};a.coraljsonp._getChannelIFrameName=
function(a){return"jsonpChannel-"+a};e.coraljsonp=a.coraljsonp.queryService;a.coraljsonp._jsonpInIFrame=function(c){var d=c.iframeName;if(!d)throw Error("no iframe name given");iframe=window.frames[d];if(!iframe){iframe=document.createElement("iframe");iframe.name=d;iframe.style.display="none";if(TelephonyUtil.isIE6)iframe.src="javascript:false;";document.body.appendChild(iframe)}window.setTimeout(function(){a.coraljsonp._jsonp(e.extend({},c,{iframeName:d}))},0)};var f=(new Date).getTime();a.coraljsonp._jsonp=
function(c){var d=e.extend({cache:!0,data:{},success:function(){},url:"",jsonp:"callback",scriptCharset:null,iframeName:null},c);c.log||a.cs.log.getLogger("coraljsonp");var b;d.iframeName&&(b=window.frames[d.iframeName]);var h=(b||window).document;if(d.cache)d.data._=(new Date).getTime();var i="amznjsonp"+f++;d.data[d.jsonp]=b?"parent."+i:i;var c=d.url+"?"+e.param(d.data),m=h.createElement("script");m.src=c;if(d.scriptCharset)m.charset=scriptCharset;window[i]=function(b){try{d.success(b)}finally{window.setTimeout(function(){window[i]=
void 0;try{delete window[i]}catch(b){}h.body.removeChild(m)},5E3)}};h.body.appendChild(m)};a.coraljsonp._drillIntoResult=function(a,d,b,h){var c,f;for(c=0;c<d.length;c++)if(f=d[c],typeof a[f]=="undefined")return h(f),null;else a=a[f];if(b)for(c=0;c<b.length;c++)if(f=b[c],typeof a[f]=="undefined")return h(f),null;return a};a.coraljsonp._registerAjaxCall=function(c){var d=c.log,b=c.timeoutMs,h=c.requestDescriptor,f=c.timeoutHandler||function(){},e=(new Date).getTime(),u=(new Date).getTime()+"_"+Math.floor(Math.random()*
1E6);if(typeof a.coraljsonp._registeredAJAXCalls=="undefined")a.coraljsonp._registeredAJAXCalls={};a.coraljsonp._registeredAJAXCalls[u]=1;if(b){var l;l=TelephonyUtil.setTimeout(function(c){if(typeof a.coraljsonp._registeredAJAXCalls[u]!="undefined"){var g=(new Date).getTime()-e;d.debug("coraljsonp timeout detected for ajax id ",u,"lateness:",c,"timeoutMs:",b,"diff:",g,"request:",h,"timeoutContext:",l);a.coraljsonp._markAjaxCallReceived(u);f()}},b)}return u};a.coraljsonp._markAjaxCallReceived=function(c){typeof a.coraljsonp._registeredAJAXCalls!=
"undefined"&&delete a.coraljsonp._registeredAJAXCalls[c]}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.cstel=="undefined")a.cstel={};a.cstel.BaseServiceClient=function(c){c=c?c:{};this.options=e.extend({serviceEnv:"prod",serviceGeo:"na",serviceHost:null,logger:null,serviceHosts:{test:{na:"",eu:"",fe:"",cn:""},master:{na:"",eu:"",fe:"",cn:""},prod:{na:"",eu:"",fe:"",cn:""}}},c);this._log=this.options.logger||a.cs.log.getLogger("baseclient");this.baseServiceUrl=this.options.serviceHost?
this.options.serviceHost:this.options.serviceHosts[this.options.serviceEnv][this.options.serviceGeo];this._cache=TelephonyUtil.createMapCache()};var c=function(a,c,d,b){return b&&!b.match(/(Timeout)/)};a.cstel.BaseServiceClient.prototype._requestJson=function(f){var g=this,f=e.extend({isCoral:!1,isUserErrorCode:c,retryDelay:1E3,maxRetries:2,retryTimeLimit:null,onSuccess:function(){}},f),d=this.baseServiceUrl;f.url&&(d+=f.url);var b=[];if(f.cacheTime){var h=d+"?"+e.param(f.params),i=this._cache.get(h);
if(i){if(f.onCacheHit)f.onCacheHit();f.onSuccess(i);return}if(f.onCacheMiss)f.onCacheMiss()}a.tel.retry.doTaskWithRetries({maxRetries:f.maxRetries,retryDelay:f.retryDelay,backoff:f.backoff,retryTimeLimit:f.retryTimeLimit,task:function(a){e.coraljsonp({params:f.params,url:d,operation:f.operation,resultNestedLocation:f.resultNestedLocation,requiredKeys:f.requiredKeys,timeout:f.timeout,logger:g.options.logger,onComplete:f.onComplete,isCoral:f.isCoral,crossDomainXhrEnabled:f.crossDomainXhrEnabled,jsonpChannel:f.jsonpChannel,
onSuccess:function(b){a(!0);f.onSuccess&&f.onSuccess.apply(this,arguments);f.cacheTime&&g._cache.put(h,b,f.cacheTime)},onError:function(d,h,c,i){if(f.isUserErrorCode(d,h,c,i)){if(a(!0),f.onError)return f.onError.apply(this,arguments)}else return b=arguments,a(!1,h=="timeout"?0:f.retryDelay)}})},onGiveUp:function(){if(f.onError)return f.onError.apply(this,b)}})};a.cstel.BaseServiceClient.prototype._requestCoralJson=function(a){var c=[];if(typeof a.hasResult=="undefined"||a.hasResult)c=[a.operation+
"Response",a.operation+"Result"],a.resultNestedLocation&&(c=c.concat(a.resultNestedLocation));a.isCoral=!0;a.resultNestedLocation=c;this._requestJson(a)}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.c2c=="undefined")a.c2c={};var c={test:{na:"https://c2c.integ.amazon.com",fe:"https://c2c-fe.integ.amazon.com",eu:"https://c2c-eu.integ.amazon.com",cn:"https://c2c-cn.integ.amazon.com"},master:{na:"https://c2c-preprod.amazon.com",fe:"https://c2c-fe-preprod.amazon.com",eu:"https://c2c-eu-preprod.amazon.com",
cn:"https://c2c-cn-preprod.amazon.com"},prod:{na:"https://c2c.amazon.com",fe:"https://c2c-fe.amazon.com",eu:"https://c2c-eu.amazon.com",cn:"https://c2c.amazon.cn"}};a.c2c.C2CServiceClient=function(e){this.constructor=a.c2c.C2CServiceClient;e=e||{};e.serviceHosts=c;a.cstel.BaseServiceClient.call(this,e)};a.c2c.C2CServiceClient.prototype=new a.cstel.BaseServiceClient;a.c2c.C2CServiceClient.prototype.requestCallStatus=function(a){this._requestCoralJson(e.extend({operation:"getCallStatus",params:{callContextId:a.callContextId,
supportAgentJoined:!0},requiredKeys:["callStatusCode"]},a))};a.c2c.C2CServiceClient.prototype.requestClick2CallStatus=function(a){if(a.c2cId)if(a.timezone)if(a.locale){var c=a.locale.match(/([a-z]{2})_?([A-Z]{2})/);c.length<3?(this._log.error("locale must match enUS or en_US format"),a.onError()):this._requestCoralJson(e.extend({operation:"getClick2CallStatus",params:{c2cId:a.c2cId,widgetVersion:"@edgeCacheVersion@",timezone:a.timezone,languageCode:c[1],countryCode:c[2]},resultNestedLocation:["click2CallStatus"],
requiredKeys:["isSkillInOpenHours","callableCountries","hoursOfOperation"]},a))}else this._log.error("missing locale"),a.onError();else this._log.error("missing timezone"),a.onError();else this._log.error("missing c2cId"),a.onError()};a.c2c.C2CServiceClient.prototype.disconnectCall=function(a){this._requestCoralJson(e.extend({operation:"disconnectCall",params:{callContextId:a.contextId},hasResult:!1},a))};a.c2c.C2CServiceClient.prototype.initiateCall=function(a){a.contextId||this._log.warn("No contextId supplied!");
var c=a.contextId;if(!c||c.length<5)c="";a.virtualCall=!!a.virtualCall;a.whenToCallMinutes=parseInt(a.whenToCallMinutes,10);if(isNaN(a.whenToCallMinutes))a.whenToCallMinutes=0;this._requestCoralJson(e.extend({operation:"initiateCall",maxRetries:0,timeout:6E3,params:{c2cId:a.c2cId,callAfterMins:a.whenToCallMinutes,"userCallbackNumber.phoneNumber":a.phoneNumber,"userCallbackNumber.country":a.countryCode,"userCallbackNumber.extensionDetails.extension":a.extension,"userCallbackNumber.extensionDetails.routeThroughReceptionist":a.viaReceptionist,
callContextId:c,virtualCall:a.virtualCall}},a))};a.c2c.C2CServiceClient.prototype.initiateChat=function(a){a.contextId||this._log.warn("No contextId supplied!");var c=a.contextId;if(!c||c.length<5)c="";var d={c2cId:a.c2cId,contextId:c,"userInfo.name":a.userName,"userInfo.initialQuestion":a.userInitialQuestion};a.allowPhoneNumberIdentifier?(j.extend(d,{"userInfo.customerIdentifier":a.customerIdentifier,"userInfo.customerIdentifierType":a.customerIdentifierType,"userInfo.pushMsgParam":a.pushMessageParam,
"userInfo.pushMsgMethod":a.pushMessageMethod}),c="initiateChatForCustomerIdentifier"):(j.extend(d,{"userInfo.email":a.customerIdentifier}),c="initiateChat");if(a.reconnectToken)d.reconnectToken=a.reconnectToken;if(a.reconnectReasonDebugMessage)d.reconnectReasonDebugMessage=a.reconnectReasonDebugMessage;this._requestCoralJson(e.extend({operation:c,params:d,requiredKeys:["chatLegId","topicUrl","keepAliveInterval"]},a))};a.c2c.C2CServiceClient.prototype.initiateWorkItem=function(a){var c=a.contextId;
if(!c||c.length<5)c="";this._requestCoralJson(e.extend({operation:"initiateWorkItem",params:{c2cId:a.c2cId,contextId:c},requiredKeys:["workItemId","contextId"]},a))};a.c2c.C2CServiceClient.prototype.emailChatTranscript=function(a){this._requestCoralJson(e.extend({operation:"emailChatTranscript",params:{chatIds:a.chatIds,c2cId:a.c2cId,transcriptToken:a.transcriptToken},hasResult:!1},a))}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.c2c=="undefined")a.c2c={};a.c2c.C2CStatusChecker=function(c){this.options=
e.extend({c2cId:null,timezone:"America/Los_Angeles",locale:"enUS",serviceEnv:"test",serviceGeo:"na",onError:function(){},cache:!0,onCacheMiss:function(){},onCacheHit:function(){},alwaysLookupHours:!1,onOutOfHours:function(){},onDisabled:function(){},onNoAgents:function(){},onAvailable:function(){},fakeInHours:!1,fakeOutOfHours:!1,fakeAgentsAvail:!1,fakeAgentsUnavail:!1,logger:null,debug:!0},c);this.options.c2cId=TelephonyUtil.sanitizeGUID(this.options.c2cId);this.cacheTime=this.options.cache?6E4:
0;this._log=this.options.logger;if(!this._log)this._log=a.cs.log.getLogger("C2CStatusChecker"),this._log.setPrefix("[C2CStatusChecker]"),this._log.setLevel(this.options.debug?"DEBUG":"WARN");this._c2cClient=new a.c2c.C2CServiceClient({serviceHost:this.options.c2cServiceHostOverride,serviceEnv:this.options.serviceEnv,serviceGeo:this.options.serviceGeo,logger:this._log})};a.c2c.C2CStatusChecker.prototype.setC2CId=function(a){this.options.c2cId=a};a.c2c.C2CStatusChecker.prototype.checkNow=function(){var a=
this;this._lookupStatus(function(e){var g=!(e.isSkillInOpenHours||a.options.fakeInHours)||a.options.fakeOutOfHours,d=!(e.areAgentsAvailable||a.options.fakeAgentsAvail)||a.options.fakeAgentsUnavail;if(e.c2cEnabled)if(g)a.options.onOutOfHours(e.hoursOfOperation,e);else if(d)a.options.onNoAgents(e.hoursOfOperation,e);else{g=null;if(e.queueTime&&e.queueTime.available)g=e.queueTime.waitTime;a.options.onAvailable(g,e.hoursOfOperation,e)}else a.options.onDisabled(e.hoursOfOperation,e)})};a.c2c.C2CStatusChecker.prototype.startPeriodicCheck=
function(a){this.stopPeriodicCheck();var e=this;this._hoursCheckInterval=window.setInterval(function(){e.checkNow()},(a||350)*1E3)};a.c2c.C2CStatusChecker.prototype.stopPeriodicCheck=function(){window.clearInterval(this._hoursCheckInterval)};a.c2c.C2CStatusChecker.prototype._lookupStatus=function(a){var e=this;this._c2cClient.requestClick2CallStatus({c2cId:this.options.c2cId,locale:this.options.locale,timezone:this.options.timezone,cacheTime:this.cacheTime,onCacheMiss:this.options.onCacheMiss,onCacheHit:this.options.onCacheHit,
onSuccess:a,onError:function(a,d,b,h){e.options.onError(a,d,b,h)}})}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.c2c=="undefined")a.c2c={};a.c2c.nextClick2CallWidgetInstanceId=0;a.c2c.click2callWidgetInstances=[];a.c2c.callStatusCodes={INITIAL:"INITIAL",PENDING:"PENDING",DIALING:"DIALING",RINGING:"RINGING",CONNECTED:"CONNECTED",AGENT_JOINED:"AGENT_JOINED",BUSY:"BUSY",NO_ANSWER:"NO_ANSWER",ERROR:"ERROR",DISCONNECTED:"DISCONNECTED",UNKNOWN:"UNKNOWN"};a.c2c.userErrors={UnknownNumberFault:"UnknownNumberFault",
NumberBlockedFault:"NumberBlockedFault",MobileNumberNotAllowedFault:"MobileNumberNotAllowedFault",InvalidNumberLengthFault:"InvalidNumberLengthFault"};a.c2c.key={ENTER:13,TAB:9,BACKSPACE:8,KEYUP:38,KEYDOWN:40,PAGEUP:33,PAGEDOWN:34};a.c2c.defaultMasks={US:"(999) 999-9999"};a.c2c.leadingZeroPrefixCountries={IT:1,VA:1,CI:1,GA:1,GQ:1,IO:1,RW:1,SB:1,SM:1};a.c2c.OTHER_COUNTRY_CODE="OTHER";a.c2c.Click2CallWidget=function(c,f){this.instanceId=a.c2c.nextClick2CallWidgetInstanceId++;a.c2c.click2callWidgetInstances.push(this);
this.options={click2TalkEnabled:!1,c2cId:null,contextGUID:null,timezone:"America/Los_Angeles",locale:"enUS",allowExtension:!0,showExtensionInstructionsOnFocus:!0,autoTab:!0,enterKeyStartsCall:!0,allowBackspaceToPreviousField:!0,preventNonNumerics:!0,callMeButtonImgSrc:"",click2TalkButtonImgSrc:"",click2TalkVideoButtonImgSrc:"",placeCallButtonImgSrc:"",loadingButtonImgSrc:"",muteButtonImgSrc:"",unmuteButtonImgSrc:"",connectingButtonImgSrc:"",connectedButtonImgSrc:"",hangingUpButtonImgSrc:"",backButtonImgSrc:"",
callMe5MinButtonImgSrc:"",hangUpButtonImgSrc:"",cancelCallButtonImgSrc:"",sortCountries:!0,whenToCallOptions:[0,5],showWhenToCallOptionsAsButtons:!1,defaultNumberFormat:[[3,3],[3,3],[4,4]],animationEnabled:!0,animationDurationMs:500,animationEasingFunction:"linear",showTimeZone:!0,showDialingCode:!0,showDialingCodeExemptCountries:{US:1,CA:1,GU:1,VG:1,VI:1,PR:1},hideDialingCodeForSingleCountry:!0,showOtherCountryOption:!1,gotoCaseSubmittedForOtherCountry:!1,showCountriesMissingName:!1,debug:!0,showErrors:!0,
serviceEnv:"test",serviceGeo:"na",protocol:"https",serviceHost:null,serviceSecureHost:null,usingTrustedCall:!1,initiateTrustedCallCallback:function(){},onCallInitializationCallback:function(){},onWidgetResetCallback:function(){},initiateC2TCallback:function(){},preInitiateCallCallback:function(){},stateChangeCallback:function(){},callStatusChangeCallback:function(){},contextGUIDChangeCallback:function(){},postValidationCallback:function(){},errorCallback:function(){},savedPhoneNumbers:{},messageOfTheDayTemplate:'<div class="c2c-messageoftheday">%s</div>',
additionalButtonMarkup:"",additionalFormMarkup:"",alwaysShowOutOfHours:!1,alwaysShowInHours:!1,alwaysShowAgentsAvail:!1,alwaysShowAgentsUnavail:!1,showDebugSection:!1,crossDomain:!0,staticJson:!1,allowCountryMasking:!1,customPhoneNumberField:null,onTheFlyValidation:!1,availableStateCallback:function(){},pollCallStatusCallback:function(){}};this.strings={initializing:"Loading...",availableHeader:"Request a call back",availableInstructions:"To talk with us, please enter your phone number.<br/>(You'll need an open phone line to receive this call)",
willReceptionistAnswer:"Will a receptionist answer this call?",extensionTip:"Enter your extension here. You can type a comma (,) to add a pause.",extensionInstructions:"Enter your extension here. You can type a comma (,) to add a pause.",otherCountryInstructions:"Please include the international dialing code for your country below.",yourNumberTip:"Enter your phone number here.",notAvailableHeader:"Call back service unavailable",notAvailableBody:"<p>At this time, our call back service is unavailable. Please contact us at 1-866-216-1072</p><p>Thank you,<br/>Amazon.com Customer Service</p>",
timedOutHeader:"We're sorry",timedOutBody:"<p>We are unable to connect with our call back service. Please check your network connection or contact us at 1-866-216-1072</p><p>Thank you,<br/>Amazon.com Customer Service</p>",queueCapExceededHeader:"We're sorry",queueCapExceededBody:"<p>Because of high call volumes, we cannot take your call at this time.</p>",outOfHoursHeader:"Talk to us... just not right now!",outOfHoursBodyTop:"<p>Our customer service representatives are available:</p>",outOfHoursBodyBottom:"<p>During normal hours, please take advantage  of our convenient callback service.</p>",
outOfHoursLoading:"",openAllDayHours:"Open all day",yes:"Yes",no:"No",labelCountry:"Country",labelYourNumber:"Your number",labelWhenToCall:"When to call",labelExtension:"Ext.",callMeButton:"Call Me",callMeButtonDisabled:"(Disabled)",callMe5MinButton:"Call Me in 5 Minutes",hangUpButton:"Hang up",cancelCallButton:"Cancel call",backButton:"Back",backButtonAlt:"Back",click2TalkButton:"Call Online",click2TalkButtonAlt:"Call Online",click2TalkButtonTip:"",availableC2THeader:"Call us online",availableC2TInstructions:"Talk to a customer service associate using your computer's microphone and internet browser.",
click2TalkVideoButton:"Call online with video",click2TalkVideoButtonAlt:"Call online with video",click2TalkVideoButtonTip:"",placeCallButton:"Place Call",placeCallButtonAlt:"Place Call",muteButton:"Mute",muteButtonAlt:"Mute",unmuteButton:"Unmute",unmuteButtonAlt:"Unmute",toggleVideoButton:"Toggle Video",toggleVideoButtonAlt:"Toggle Video",connectingButton:"Connecting...",connectingButtonAlt:"Connecting...",connectedButton:"Connected...",connectedButtonAlt:"Connected...",hangingUpButton:"Hanging Up...",
hangingUpButtonAlt:"Hanging Up...",loadingButton:"Loading...",loadingButtonAlt:"Loading...",micErrorMessage:"No microphone found. Please connect a microphone and place call again.",micWebcamErrorMessage:"No microphone or webcam found. Please connect a microphone and webcam and place call again.",connectivityStatusGood:"Good",connectivityStatusWeak:"Weak",connectivityStatusBad:"Bad",connectivityStatusUnknown:"Unknown",connectivityMeter:"Connectivity:",callMeButtonAlt:"Call Me",callMeButtonTip:"",callMeButtonDisabledAlt:"(Disabled)",
callMeButtonDisabledTip:"Finish entering your number",hangUpButtonAlt:"Hang up",cancelCallButtonAlt:"Cancel call",estimateWait1Min:"Estimated wait: 1 minute",estimateWaitTime:"Estimated wait: %s minutes",whenToCallOptionNow:"Now",whenToCallOptionLater:"In %s minutes",startWebcallHeader:"Call Amazon Online",startWebcallMessage:"When ready, click Place Call to speak with Amazon Customer Service.<br/>Make sure to have your computer's microphone and speakers turned on.",startWebcallStatus:"",virtualQueueHeader:"Waiting in line...",
virtualQueueMessage:"When you phone rings, please answer it.<br/>You will hear ringing until the other party answers. ",virtualQueueStatus:"You are currently in line for us to call you. Thanks for your patience!",connectingHeader:"Connecting...",connectingMessage:"When you phone rings, please answer it.<br/>You will hear ringing until the other party answers. ",connectingStatus:"Connecting your call...",ringingHeader:"Connecting...",ringingMessage:"When you phone rings, please answer it.<br/>You will hear ringing until the other party answers.",
ringingStatus:"Ringing...",connectedHeader:"Call connected",connectedMessage:"",connectedStatus:"Your call is now connected.",connectedAndReattachedHeader:"Call in progress",connectedAndReattachedMessage:"",connectedAndReattachedStatus:"Your call is still connected.",pendingHeader:"Waiting to call you",pendingMessage:"",pendingStatus:"... in about %s minute",pendingStatusPlural:"... in about %s minutes",pendingStatusWaitUnknown:"... at the time you have set.",callEndedHeader:"Call ended",callEndedMessage:"<p>Your call with us has ended.</p><p>If you need to speak with us again, please <a %s>click here</a> to place another call.</p><p>Thank you,<br/>Amazon.com Customer Service.</p>",
userErrorNumberBlockedFaultHeader:"We're sorry",userErrorNumberBlockedFaultMessage:"<p>Your number has been blocked from receiving calls from our call back service.</p><p>Please contact 1-866-216-1072 for help with this.</p>",userErrorUnknownNumberFaultHeader:"We're sorry",userErrorUnknownNumberFaultMessage:"<p>Our call back service has no knowledge of the area code you have entered.</p><p>Please <a %s>try a different number</a> or contact 1-866-216-1072.</p>",userErrorMobileNumberNotAllowedFaultHeader:"We're sorry",
userErrorMobileNumberNotAllowedFaultMessage:"<p>We cannot dial out to a cell phone number.</p><p>Please <a %s>click here</a> to place a call to a different phone number.</p>",userErrorInvalidNumberLengthFaultHeader:"We're sorry",userErrorInvalidNumberLengthFaultMessage:"<p>The number you have entered appears to be invalid.</p></p><p>Please <a %s>try a different number</a> or contact 1-866-216-1072.</p>",userInternalFailureFaultHeader:"We're sorry",userInternalFailureFaultMessage:"<p>An unexpected error occured.</p>",
invalidCharsError:"Please only enter numbers (0-9) in the fields below.",invalidCharsExtensionError:"Please only enter numbers (0-9), #, * or a comma (,) in your extension below.",tooShortError:"Please enter at least %s digits in the field below.",tooLongError:"Please enter no more than %s digits in the field below.",callStatusUpdateError:"Oops! We are having trouble updating the status of your call.",caseSubmittedHeader:"Thank you",caseSubmittedMessage:"<p>A customer service representive will call you shortly.</p>",
dialingCodePrefix:"+",areaCodeLeft:"(",areaCodeRight:")",numberDelimiter:"-",dayRangeDelimiter:"-",dayRangeTerminator:":",hourRangeDelimiter:" - ",hourRangeListDelimiter:", ",am:"AM",pm:"PM",midnight:"Midnight",noon:"Noon",everyDayOfTheWeek:"Every day of the week",dayNameMonday:"Monday",dayNameTuesday:"Tuesday",dayNameWednesday:"Wednesday",dayNameThursday:"Thursday",dayNameFriday:"Friday",dayNameSaturday:"Saturday",dayNameSunday:"Sunday","tzNameAmerica/Los_Angeles":"Pacific","tzNameEurope/London":"London",
"tzNameEurope/Paris":"Paris","tzNameEurope/Berlin":"Berlin","tzNameAsia/Tokyo":"Tokyo",countryNameOTHER:"Other...",countryNameAD:"Andorra",countryNameAE:"United Arab Emirates",countryNameAF:"Afghanistan",countryNameAL:"Albania",countryNameAM:"Armenia",countryNameAO:"Angola",countryNameAR:"Argentina",countryNameAT:"Austria",countryNameAU:"Australia",countryNameAW:"Aruba",countryNameAZ:"Azerbaijan",countryNameBA:"Bosnia and Herzegovina",countryNameBD:"Bangladesh",countryNameBE:"Belgium",countryNameBF:"Burkina Faso",
countryNameBG:"Bulgaria",countryNameBH:"Bahrain",countryNameBJ:"Benin",countryNameBN:"Brunei",countryNameBO:"Bolivia",countryNameBR:"Brazil",countryNameBS:"The Bahamas",countryNameBW:"Botswana",countryNameBY:"Belarus",countryNameCA:"Canada",countryNameCD:"Democratic Republic of the Congo",countryNameCG:"Republic of the Congo",countryNameCH:"Switzerland",countryNameCI:"Ivory Coast",countryNameCL:"Chile",countryNameCM:"Cameroon",countryNameCN:"China",countryNameCO:"Colombia",countryNameCR:"Costa Rica",
countryNameCU:"Cuba",countryNameCY:"Cyprus",countryNameCZ:"Czech Republic",countryNameDE:"Germany",countryNameDJ:"Djibouti",countryNameDK:"Denmark",countryNameDO:"Dominican Republic",countryNameDZ:"Algeria",countryNameEC:"Ecuador",countryNameEE:"Estonia",countryNameEG:"Egypt",countryNameER:"Eritrea",countryNameES:"Spain",countryNameET:"Ethiopia",countryNameFI:"Finland",countryNameFR:"France",countryNameGA:"Gabon",countryNameGB:"United Kingdom",countryNameGE:"Georgia",countryNameGG:"Guernsey",countryNameGH:"Ghana",
countryNameGM:"Gambia",countryNameGN:"Guinea",countryNameGQ:"Equatorial Guinea",countryNameGR:"Greece",countryNameGT:"Guatemala",countryNameGU:"Guam",countryNameHK:"Hong Kong",countryNameHN:"Honduras",countryNameHR:"Croatia",countryNameHT:"Haiti",countryNameHU:"Hungary",countryNameID:"Indonesia",countryNameIE:"Ireland",countryNameIL:"Israel",countryNameIM:"Isle of Man",countryNameIN:"India",countryNameIQ:"Iraq",countryNameIR:"Iran",countryNameIS:"Iceland",countryNameIT:"Italy",countryNameJE:"Jersey",
countryNameJM:"Jamaica",countryNameJO:"Jordan",countryNameJP:"Japan",countryNameKE:"Kenya",countryNameKG:"Kyrgyzstan",countryNameKH:"Cambodia",countryNameKP:"North Korea",countryNameKR:"South Korea",countryNameKW:"Kuwait",countryNameKZ:"Kazakhstan",countryNameLA:"Laos",countryNameLB:"Lebanon",countryNameLI:"Liechtenstein",countryNameLK:"Sri Lanka",countryNameLT:"Lithuania",countryNameLU:"Luxembourg",countryNameLV:"Latvia",countryNameLY:"Libya",countryNameMA:"Morocco",countryNameMC:"Monaco",countryNameMD:"Moldova",
countryNameME:"Montenegro",countryNameMG:"Madagascar",countryNameMK:"Macedonia",countryNameML:"Mali",countryNameMM:"Burma",countryNameMN:"Mongolia",countryNameMO:"Macau",countryNameMR:"Mauritania",countryNameMT:"Malta",countryNameMU:"Mauritius",countryNameMV:"Maldives",countryNameMW:"Malawi",countryNameMX:"Mexico",countryNameMY:"Malaysia",countryNameMZ:"Mozambique",countryNameNA:"Namibia",countryNameNE:"Niger",countryNameNG:"Nigeria",countryNameNI:"Nicaragua",countryNameNL:"Netherlands",countryNameNO:"Norway",
countryNameNP:"Nepal",countryNameNZ:"New Zealand",countryNameOM:"Oman",countryNamePA:"Panama",countryNamePE:"Peru",countryNamePG:"Papua New Guinea",countryNamePH:"Philippines",countryNamePK:"Pakistan",countryNamePL:"Poland",countryNamePR:"Puerto Rico",countryNamePS:"West Bank and Gaza",countryNamePT:"Portugal",countryNamePY:"Paraguay",countryNameQA:"Qatar",countryNameRO:"Romania",countryNameRS:"Serbia",countryNameRU:"Russia",countryNameSA:"Saudi Arabia",countryNameSD:"Sudan",countryNameSE:"Sweden",
countryNameSG:"Singapore",countryNameSI:"Slovenia",countryNameSK:"Slovakia",countryNameSL:"Sierra Leone",countryNameSM:"San Marino",countryNameSN:"Senegal",countryNameSO:"Somalia",countryNameSV:"El Salvador",countryNameSY:"Syria",countryNameTD:"Chad",countryNameTH:"Thailand",countryNameTJ:"Tajikistan",countryNameTM:"Turkmenistan",countryNameTN:"Tunisia",countryNameTR:"Turkey",countryNameTT:"Trinidad and Tobago",countryNameTW:"Taiwan",countryNameTZ:"Tanzania",countryNameUA:"Ukraine",countryNameUG:"Uganda",
countryNameUS:"United States",countryNameUY:"Uruguay",countryNameUZ:"Uzbekistan",countryNameVA:"Vatican City",countryNameVE:"Venezuela",countryNameVG:"Virgin Islands, British",countryNameVI:"Virgin Islands, U.S.",countryNameVN:"Vietnam",countryNameYE:"Yemen",countryNameZA:"South Africa",countryNameZM:"Zambia",countryNameZW:"Zimbabwe"};this.states={initial:{},available:{},outOfHours:{},callInProgress:{},callEnded:{},notAvailable:{},queueCapExceeded:{},timedOut:{},userError:{},caseSubmitted:{}};for(var g in this.states)this.states[g].id=
g;this.useVirtualQueue=!1;this.waitTimeEstimateMessage=null;this.startingWebcall=this.canWebcall=this.videoCallClicked=this.isWebcallVideoEnabled=this.isWebcallEnabled=!1;this.userErrorCode=this.audioContext=null;this.container=c;this.callStatusPollDelay=2E3;this.callStatusRetriesBeforeError=3;this.callStatusRetriesBeforeGivingUp=6;f.c2cId=TelephonyUtil.sanitizeGUID(f.c2cId);f.contextGUID=TelephonyUtil.sanitizeGUID(f.contextGUID);f&&(e.extend(this.options,f),e.extend(this.strings,f.strings));f&&e.extend(this.urls,
f.urls);if(!f.strings||!f.strings.callMeButton)this.strings.callMeButton='<img src="'+this.options.callMeButtonImgSrc+'" alt="'+this.strings.callMeButtonAlt+'" title="'+this.strings.callMeButtonTip+'"/>';if(!f.strings||!f.strings.callMeButtonDisabled)this.strings.callMeButtonDisabled='<img src="'+this.options.callMeButtonDisabledImgSrc+'" alt="'+this.strings.callMeButtonAlt+'" title="'+this.strings.callMeButtonTip+'"/>';if(!f.strings||!f.strings.cancelCallButton)this.strings.cancelCallButton='<img src="'+
this.options.cancelCallButtonImgSrc+'" alt="'+this.strings.cancelCallButtonAlt+'"/>';if(!f.strings||!f.strings.hangUpButton)this.strings.hangUpButton='<img src="'+this.options.hangUpButtonImgSrc+'" alt="'+this.strings.hangUpButtonAlt+'"/>';if(!f.strings||!f.strings.backButton)this.strings.backButton='<img src="'+this.options.backButtonImgSrc+'" alt="'+this.strings.backButtonAlt+'"/>';if(!f.strings||!f.strings.click2TalkButton)this.strings.click2TalkButton='<img src="'+this.options.click2TalkButtonImgSrc+
'" alt="'+this.strings.click2TalkButtonAlt+'" title="'+this.strings.click2TalkButtonTip+'"/>';if(!f.strings||!f.strings.placeCallButton)this.strings.placeCallButton='<img src="'+this.options.placeCallButtonImgSrc+'" alt="'+this.strings.placeCallButtonAlt+'"/>';if(!f.strings||!f.strings.connectingButton)this.strings.connectingButton='<img src="'+this.options.connectingButtonImgSrc+'" alt="'+this.strings.connectingButtonAlt+'"/>';if(!f.strings||!f.strings.connectedButton)this.strings.connectedButton=
'<img src="'+this.options.connectedButtonImgSrc+'" alt="'+this.strings.connectedButtonAlt+'"/>';if(!f.strings||!f.strings.hangingUpButton)this.strings.hangingUpButton='<img src="'+this.options.hangingUpButtonImgSrc+'" alt="'+this.strings.hangingUpButtonAlt+'"/>';if(!f.strings||!f.strings.loadingButton)this.strings.loadingButton='<img src="'+this.options.loadingButtonImgSrc+'" alt="'+this.strings.loadingButtonAlt+'"/>';if(!f.strings||!f.strings.click2TalkVideoButton)this.strings.click2TalkVideoButton=
'<img src="'+this.options.click2TalkVideoButtonImgSrc+'" alt="'+this.strings.click2TalkVideoButtonAlt+'" title="'+this.strings.click2TalkVideoButtonTip+'"/>';this.log=a.cs.log.getLogger("click2call");this.log.setPrefix("[c2c]");this.options.showErrors?this.options.debug||this.log.setLevel("WARN"):this.log.setLevel("OFF");if(g=TelephonyUtil.getFromLocalStorage("c2cSavedPhoneNumbers"))this.log.debug("Existing numbers:",g),this.options.savedPhoneNumbers=e.extend({},g,this.options.savedPhoneNumbers);
this.savedPhoneNumbers=this.options.savedPhoneNumbers;this.hoursOfOperation=null;this.c2cClient=new a.c2c.C2CServiceClient({serviceEnv:this.options.serviceEnv,serviceGeo:this.options.serviceGeo,protocol:this.options.protocol,serviceHost:this.options.serviceHost,logger:this.log});this.states.initial.template='<p><div class="c2c-loader"> </div>'+this.strings.initializing+"</p>"+this.options.additionalButtonMarkup;this.states.notAvailable.template='<h3><div class="c2c-errorLine">'+this.strings.notAvailableHeader+
"</div></h3>"+this.strings.notAvailableBody+this.options.additionalButtonMarkup;this.states.queueCapExceeded.template='<h3><div class="c2c-errorLine">'+this.strings.queueCapExceededHeader+"</div></h3>"+this.strings.queueCapExceededBody+this.options.additionalButtonMarkup;this.states.timedOut.template='<h3><div class="c2c-errorLine">'+(this.strings.timedOutHeader||this.strings.notAvailableHeader)+"</div></h3>"+(this.strings.timedOutBody||this.strings.notAvailableBody)+this.options.additionalButtonMarkup;
this.states.outOfHours.template="<h3>"+this.strings.outOfHoursHeader+"</h3>"+this.strings.outOfHoursBodyTop+'<div class="c2c-hours">'+this.strings.outOfHoursLoading+"</div>"+this.strings.outOfHoursBodyBottom+this.options.additionalButtonMarkup;this.states.available.template="<h3>"+this.strings.availableHeader+"</h3><p>"+this.strings.availableInstructions+'</p><div class="c2c-form-row c2c-form-row-country"><label for="c2c-country'+this.instanceId+'">'+this.strings.labelCountry+'</label><label class="c2c-selectlabel"><select class="c2c-country" id="c2c-country'+
this.instanceId+'"></select></label></div><div class="c2c-number-validation-error c2c-errorLine" style="display: none"></div><div class="c2c-other-country-instructions c2c-warningLine" style="display: none">'+this.strings.otherCountryInstructions+'</div><div class="c2c-extension-instructions c2c-warningLine" style="display: none">'+this.strings.extensionInstructions+'</div><div class="c2c-form-row c2c-form-row-yournumber c2c-specific-country-elements"><label for="c2c-yournumber-'+this.instanceId+
'">'+this.strings.labelYourNumber+'</label><span class="c2c-dialing-code"></span><span class="c2c-yournumber-container"></span><span class="c2c-extension-container"><label class="c2c-extension-label" for="c2c-extension-'+this.instanceId+'">   '+this.strings.labelExtension+'</label><input class="c2c-extension" id="c2c-extension-'+this.instanceId+'" type="tel" title="'+this.strings.extensionTip+'"></input></span></div><div class="c2c-form-row c2c-form-row-whentocall"><label for="c2c-whentocall-'+this.instanceId+
'">'+this.strings.labelWhenToCall+'</label><select class="c2c-whentocall" id="c2c-whentocall-'+this.instanceId+'"></select></div><div class="c2c-form-row c2c-form-row-receptionist" style="display: none"><span class="c2c-receptionist-prompt">'+this.strings.willReceptionistAnswer+'</span><input type="radio" name="c2c-receptionist-radio" class="c2c-receptionist-radio" checked value="0"></input> '+this.strings.no+'<input type="radio" name="c2c-receptionist-radio" class="c2c-receptionist-radio" value="1"></input> '+
this.strings.yes+"</div>"+this.options.additionalFormMarkup+'<div class="c2c-callme-wait-time-estimate c2c-specific-country-elements"></div><div class="c2c-form-row c2c-form-row-callme-button c2c-specific-country-elements"><span class="c2c-callme-button-spacer"></span><a href="#" class="c2c-callme-button">'+this.strings.callMeButton+"</a>"+(this.options.onTheFlyValidation?'<span class="c2c-callme-button-disabled">'+this.strings.callMeButtonDisabled+"</span>":"")+'<span class="c2c-callme-whentocall-buttons"></span>'+
this.options.additionalButtonMarkup+"</div>";this.states.available.template+="</div>";this.states.callInProgress.template='<h3 class="c2c-inprogress-header"></h3><span class="c2c-inprogress-message"></span><div class="c2c-inprogress-status"><div class="c2c-inprogress-status-message"></div><div class="webcall-container" style="display:none"></div></div><div class="c2c-inprogress-update-error c2c-errorLine" style="display:none">'+this.strings.callStatusUpdateError+'</div><div class="c2c-inprogress-wait-time-estimate"></div><span class="c2c-hangup-button-spacer"></span><a href="#" class="c2c-hangup-button" style="display:none">'+
this.strings.hangUpButton+'</a><a href="#" class="c2c-cancelcall-button" style="display:none">'+this.strings.cancelCallButton+'</a><a href="#" class="c2c-back-button" style="display:none">'+this.strings.backButton+"</a>"+this.options.additionalButtonMarkup;this.states.callEnded.template='<h3 class="c2c-successLine c2c-callended-header">'+this.strings.callEndedHeader+'</h3><span class="c2c-callended-message">'+this.strings.callEndedMessage.replace(/%s/,'href="#" class="c2c-call-again-link"')+"</span>"+
this.options.additionalButtonMarkup;this.states.userError.template='<h3 class="c2c-errorLine c2c-usererror-header"></h3><span class="c2c-usererror-message"></span>'+this.options.additionalButtonMarkup;this.states.caseSubmitted.template='<h3 class="c2c-successLine c2c-casesubmitted-header">'+this.strings.caseSubmittedHeader+'</h3><span class="c2c-casesubmitted-message">'+this.strings.caseSubmittedMessage+"</span>"};a.c2c.Click2CallWidget.prototype.updatec2cId=function(a){this.options.c2cId=TelephonyUtil.sanitizeGUID(a)};
a.c2c.Click2CallWidget.prototype.initialize=function(){this._setState(this.states.initial)};a.c2c.Click2CallWidget.prototype.getString=function(a){return this.strings[a]};a.c2c.Click2CallWidget.prototype.setContextGUID=function(a){this.options.contextGUID=a;typeof this.options.contextGUIDChangeCallback=="function"&&this.options.contextGUIDChangeCallback(a)};a.c2c.Click2CallWidget.prototype.getInstanceId=function(){return this.instanceId};a.c2c.Click2CallWidget.prototype._find=function(a){return e(this.container).find(a)};
a.c2c.Click2CallWidget.prototype._raiseEvent=function(a,f){f.widget=this;e(document).trigger("Click2Call/"+a,f)};a.c2c.Click2CallWidget.prototype._setCallStatus=function(a){this.callStatus=a;typeof this.options.callStatusChangeCallback=="function"&&(this.options.callStatusChangeCallback(a),this._raiseEvent("CallStatusChange",{status:a}));this.log.debug("call status change: ",a)};a.c2c.Click2CallWidget.prototype._error=function(a){this.options.showErrors&&this.log.error(a);this.timedOut?this._setState(this.states.timedOut):
this._setState(this.states.notAvailable);this.options.errorCallback(a);this._raiseEvent("Error",{message:a})};a.c2c.Click2CallWidget.prototype._requestCallStatus=function(a,e){this.c2cClient.requestCallStatus({callContextId:this.options.contextGUID,onSuccess:a,onError:e,maxRetries:0})};a.c2c.Click2CallWidget.prototype._requestClick2CallStatus=function(a,e){this.c2cClient.requestClick2CallStatus({c2cId:this.options.c2cId,timezone:this.options.timezone,locale:this.options.locale,onSuccess:a,onError:e})};
a.c2c.Click2CallWidget.prototype._disconnectCall=function(a,e){this.c2cClient.disconnectCall({contextId:this.options.contextGUID,onSuccess:a,onError:e});this._setState(this.states.callEnded)};a.c2c.Click2CallWidget.prototype._clearPhoneNumberErrors=function(){this._find(".c2c-number-validation-error").hide();this._find(".c2c-invalid-field").removeClass("c2c-invalid-field")};a.c2c.Click2CallWidget.prototype._validatePhoneNumberFields=function(){var c=!1,f=[],g=[],d=[];this._getPhoneNumberFormat();
this._find("input.c2c-yournumber").each(function(){e(this).removeClass("c2c-invalid-field");for(var b=this.getFieldObject().validate(),h=0;h<b.length;h++){var c=b[h];c.constructor==a.c2c.InvalidCharsValidationError?f.push(c):c.constructor==a.c2c.TooShortValidationError?g.push(c):c.constructor==a.c2c.TooLongValidationError&&d.push(c)}});this._find("input.c2c-extension").each(function(){e(this).removeClass("c2c-invalid-field");e(this).val().match(/^[\d,#\*]*$/)||(c=!0)});var b=null,h=[];if(f.length>
0)for(var b=f[0].getMessage(),i=0;i<f.length;i++)h.push(f[i].getFieldInError().getDomElement());else if(g.length>0)b=g[0].getMessage(),h.push(g[0].getFieldInError().getDomElement());else if(d.length>0)b=d[0].getMessage(),h.push(d[0].getFieldInError().getDomElement());else if(c)b=this.strings.invalidCharsExtensionError,h=this._find("input.c2c-extension");e.each(h,function(){e(this).addClass("c2c-invalid-field")});b&&this._animateShow(e(this.container).find(".c2c-number-validation-error").html(b));
return!b};a.c2c.Click2CallWidget.prototype._animateShow=function(a){e(a).amznSafeShow({animate:this.options.animationEnabled,durationMs:this.options.animationDurationMs,easingFunction:this.options.animationEasingFunction})};a.c2c.Click2CallWidget.prototype._animateHide=function(a){e(a).amznSafeHide({animate:this.options.animationEnabled,durationMs:this.options.animationDurationMs,easingFunction:this.options.animationEasingFunction})};a.c2c.Click2CallWidget.prototype.postInitiateCallCallback=function(c){return c&&
typeof c.contextId=="string"&&c.contextId.length>0?(this.setContextGUID(c.contextId),!1):c&&typeof c.callContextId=="string"&&c.callContextId.length>0?(this.setContextGUID(c.callContextId),!1):(this._setState(this.states.notAvailable),c&&typeof a.c2c.userErrors[c.error]!="undefined"?(this.userErrorCode=c.error,this._setState(this.states.userError)):this._error("Failed to call - non-user error: "+(c?c.error:"no response sent")),!0)};a.c2c.Click2CallWidget.prototype._trustedCall=function(a,e,g,d,b){var h=
this;this.options.onCallInitializationCallback();var i=this.options.initiateTrustedCallCallback(this,{phoneNumber:a,country:e,extensionDetails:{extension:g,routeThroughReceptionist:d}},{callAfterMins:parseInt(b,10),virtualCall:!!h.useVirtualQueue});if(i&&typeof i.onloadend!="undefined"){var m=i.onloadend;i.onloadend=function(){var b=JSON.parse(i.response);h.postInitiateCallCallback(b);typeof m=="function"&&m();return i}}else if(i&&typeof i.done=="function")i.done(function(b){h.postInitiateCallCallback(b);
return i});else return h.postInitiateCallCallback(i),i};a.c2c.Click2CallWidget.prototype._call=function(a,e,g,d,b,h){var i={},m=this;this.options.preInitiateCallCallback(this,{base:h,countryCode:e,ext:g,receptionist:d});this.c2cClient.initiateCall({c2cId:this.options.c2cId,contextId:this.options.contextGUID,whenToCallMinutes:b,phoneNumber:a,countryCode:e,extension:g,viaReceptionist:d,virtualCall:!!this.useVirtualQueue,onSuccess:function(b){i=b;m.postInitiateCallCallback(i)},onError:function(b,a,d,
h){m.postInitiateCallCallback({error:h});i=""}});return i};a.c2c.Click2CallWidget.prototype._initiateCall=function(c){if(this._validatePhoneNumberFields()){this._savePhoneNumber();typeof c==="undefined"&&(c=this.options.showWhenToCallOptionsAsButtons?0:this._find("select.c2c-whentocall").val());this.callInitiatedTime=(new Date).getTime();var e=this._getCurrentCountry();this.estimatedCallBackTime=this.callInitiatedTime+c*6E4;var g=this._find("input"),d=g.filter(".c2c-extension").val(),b=!1;d&&(b=g.filter('.c2c-receptionist-radio[value="1"]').is(":checked"));
var h=[];g.filter(".c2c-yournumber").each(function(){var b=this.getFieldObject().getValue();h.push(b)});g=h.join("");if(!(typeof this.options.postValidationCallback==="function"&&!1===this.options.postValidationCallback(this,g))){this.callStatusPollingEnabled=this.reattached=!1;e!==a.c2c.OTHER_COUNTRY_CODE&&(this._setCallStatus(c===0?a.c2c.callStatusCodes.DIALING:a.c2c.callStatusCodes.PENDING),this._setState(this.states.callInProgress));var i={};if((i=this.options.usingTrustedCall?this._trustedCall(g,
e,d,b,c):this._call(g,e,d,b,c,h))&&typeof i.callStatusPollDelay!="undefined")this.callStatusPollDelay=i.callStatusPollDelay;this.callStatusPollingEnabled=!0;e===a.c2c.OTHER_COUNTRY_CODE&&this.options.gotoCaseSubmittedForOtherCountry&&this._setState(this.states.caseSubmitted)}}};a.c2c.Click2CallWidget.prototype._tryPopulateWaitTimeEstimate=function(a){a=this._find(a);if(a===null)return!1;if(this.waitTimeEstimateMessage===null)return a.empty(),!1;this.log.debug(this.waitTimeEstimateMessage);a.html(this.waitTimeEstimateMessage);
return!0};a.c2c.Click2CallWidget.prototype._populateWhenToCall=function(){for(var a=this,f=this._find(".c2c-whentocall"),g=this._find(".c2c-callme-whentocall-buttons"),d=0;d<this.options.whenToCallOptions.length;d++){var b=this.options.whenToCallOptions[d];if(!(a.timeToClosing!=null&&a.timeToClosing<b*6E4))if(this.options.showWhenToCallOptionsAsButtons){if(b!==0){var h=document.createElement("a");h.href="#";h.className="c2c-callme-later-button c2c-callme-in-"+b+"min-button";e(h).html(this.strings["callMe"+
b+"MinButton"]);e(h).click(function(d){a._initiateCall(b);d.preventDefault()});g.append(h)}}else h=b===0?this.strings.whenToCallOptionNow:this.strings.whenToCallOptionLater.replace(/%s/,b),f.append('<option value="'+b+'">'+h+"</option>")}};a.c2c.Click2CallWidget.prototype._populateCountries=function(){var c=this._find(".c2c-country");this.fixedCountryCode=null;if(this.countryCodesInOrder&&this.countryCodesInOrder.length==1)this.fixedCountryCode=this.countryCodesInOrder[1],this._find(".c2c-form-row-country").hide();
for(var e=[],g=this.countryCodesInOrder.length,d=0;d<g;d++){var b=this.countryCodesInOrder[d],h=this.strings["countryName"+b];h?e.push({code:b,name:h}):this.options.showCountriesMissingName&&e.push({code:b,name:b})}g=e.slice(1);this.options.sortCountries&&g.sort(function(b,d){return b.code===a.c2c.OTHER_COUNTRY_CODE?1:d.code===a.c2c.OTHER_COUNTRY_CODE?-1:b.name.localeCompare(d.name)>0?1:b.name.localeCompare(d.name)<0?-1:0});e=[e[0]].concat(g);g=e.length;for(d=0;d<g;d++)b=e[d],c.append('<option value="'+
b.code+'">'+b.name+"</option>")};a.c2c.Click2CallWidget.prototype._savePhoneNumberValues=function(a,e,g,d){this.savedPhoneNumbers[a]={base:e,ext:g,receptionist:d};TelephonyUtil.putInLocalStorage("c2cSavedPhoneNumbers",this.savedPhoneNumbers);TelephonyUtil.putInLocalStorage("c2cSavedLastCountry",a)};a.c2c.Click2CallWidget.prototype._savePhoneNumber=function(){var a=this._getCurrentCountry(),f=[];this._find("input.c2c-yournumber").each(function(){f.push(e(this).val())});var g=this._find("input.c2c-extension").val(),
d=this._find('input.c2c-receptionist-radio[value="1"]').is(":checked");this._savePhoneNumberValues(a,f,g,d)};a.c2c.Click2CallWidget.prototype._restorePhoneNumber=function(){var a=this.savedPhoneNumbers[this._getCurrentCountry()];a&&(this._find("input.c2c-yournumber").each(function(f){(f=a.base[f])&&e(this).val(f)}),this.options.allowExtension&&this._find("input.c2c-extension").val(a.ext),typeof a.ext=="string"&&a.ext.length>0&&this.options.allowExtension?this._find("div.c2c-form-row-receptionist").show():
this._find("div.c2c-form-row-receptionist").hide(),a.receptionist?this._find('input.c2c-receptionist-radio[value="1"]').attr("checked",!0):this._find('input.c2c-receptionist-radio[value="0"]').attr("checked",!0))};a.c2c.Click2CallWidget.prototype._getNumberField=function(a){var a=a[1],e=document.createElement("input");e.id="c2c-yournumber-"+this.instanceId;e.className="c2c-yournumber";e.type="text";e.maxLength=a;e.style.width=a+"em";e.title=this.strings.yourNumberTip;return e};a.c2c.Click2CallWidget.prototype._getCurrentCountry=
function(){return this.fixedCountryCode?this.fixedCountryCode:this._find(".c2c-country").val()};a.c2c.Click2CallWidget.prototype._getCurrentCountryConfig=function(){return this.callableCountries[this._getCurrentCountry()]};a.c2c.Click2CallWidget.prototype._getPhoneNumberFormat=function(a){return(a||this._getCurrentCountryConfig()).fields||this.options.defaultNumberFormat};a.c2c.Click2CallWidget.prototype._updateNumberFormat=function(){var c=this._find(".c2c-yournumber-container");c.empty();var f=
this._getCurrentCountryConfig(),g=this._getPhoneNumberFormat(f);this.options.showDialingCode&&!this.options.showDialingCodeExemptCountries[f.countryCode]&&!(this.countryCodesInOrder.length==1&&this.options.hideDialingCodeForSingleCountry)?this._find("span.c2c-dialing-code").show().html(this.strings.dialingCodePrefix+f.dialingCode):this._find("span.c2c-dialing-code").hide();this._getCurrentCountry();if(this.options.allowCountryMasking&&g.length==3&&g[0].minLength==3&&g[0].maxLength==3&&g[1].minLength==
3&&g[1].maxLength==3&&g[2].minLength==4&&g[2].maxLength==4)c.append((new a.c2c.SinglePhoneNumberField({minLength:10,maxLength:10},this)).getDomElement()),c.children(".c2c-yournumber").mask(a.c2c.defaultMasks.US,{placeholder:" "});else if(g.length>1){c.append(this.strings.areaCodeLeft);var d=(new a.c2c.DividedPhoneNumberField(g[0],this)).getDomElement();c.append(d);f.defaultAreaCode&&e(d).val(f.defaultAreaCode);c.append(this.strings.areaCodeRight);for(d=1;d<g.length;d++)d!=1&&c.append(this.strings.numberDelimiter),
c.append((new a.c2c.DividedPhoneNumberField(g[d],this)).getDomElement())}else c.append((new a.c2c.SinglePhoneNumberField(g[0],this)).getDomElement());this.options.autoTab&&c.children(".c2c-yournumber").keyup(function(b){this.value.length==this.maxLength&&b.which>32&&e(this).next(".c2c-yournumber").focus().select().attr("justEntered","true")});var b=this,d=function(d){setTimeout(function(){b._validatePhoneNumberFields()?(e(".c2c-callme-button").show(),e(".c2c-callme-button-disabled").hide()):(e(".c2c-callme-button").hide(),
e(".c2c-callme-button-disabled").show());(!d||!(d.which==a.c2c.key.ENTER&&b.options.enterKeyStartsCall))&&b._clearPhoneNumberErrors()},5)},c=c.children("input[type=text], input[type=tel]").keydown(function(d){if(d.which==a.c2c.key.ENTER&&b.options.enterKeyStartsCall)b._initiateCall();else if(b.options.allowBackspaceToPreviousField&&d.which===a.c2c.key.BACKSPACE&&this.value.length===0){var c=e(this).prev(".c2c-yournumber");c.focus();c.focus().val(c.val())}b.options.autoTab&&e(this).attr("justEntered")==
"true"&&(d.which==a.c2c.key.TAB&&d.preventDefault(),e(this).attr("justEntered","false"));b.options.preventNonNumerics&&g.length>1&&(d.which==109||d.which==189||d.which==190||d.which==110||d.which==57&&d.shiftKey||d.which==48&&d.shiftKey)&&d.preventDefault()});b.options.onTheFlyValidation&&(c.change(d).keypress(d).keydown(d).focus(d).blur(d).click(d).bind("paste",d).bind("cut",d),d());this._clearPhoneNumberErrors();f.countryCode===a.c2c.OTHER_COUNTRY_CODE?b._animateShow(e(this.container).find("div.c2c-other-country-instructions")):
b._animateHide(e(this.container).find("div.c2c-other-country-instructions"));this._find(".c2c-extension").val("")};a.c2c.Click2CallWidget.prototype._isCallInProgress=function(){switch(this.callStatus){case a.c2c.callStatusCodes.INITIAL:case a.c2c.callStatusCodes.PENDING:case a.c2c.callStatusCodes.DIALING:case a.c2c.callStatusCodes.RINGING:case a.c2c.callStatusCodes.CONNECTED:case a.c2c.callStatusCodes.AGENT_JOINED:return!0;default:return!1}};a.c2c.Click2CallWidget.prototype._isCallWaiting=function(){switch(this.callStatus){case a.c2c.callStatusCodes.INITIAL:case a.c2c.callStatusCodes.PENDING:case a.c2c.callStatusCodes.CONNECTED:return!0;
default:return!1}};a.c2c.Click2CallWidget.prototype._isCustomerConnected=function(){return this.callStatus===a.c2c.callStatusCodes.CONNECTED};a.c2c.Click2CallWidget.prototype._isCallEnded=function(){return!this._isCallInProgress()&&this.callStatus!=a.c2c.callStatusCodes.INITIAL&&this.callStatus!=a.c2c.callStatusCodes.UNKNOWN};a.c2c.Click2CallWidget.prototype._postRenderInitialState=function(){var c=this;if(navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|IEMobile)/))c.canWebcall=!1;
else if(window.chrome&&c.options.click2TalkEnabled){if(c.canWebcall=!0,c.audioContext===null)c.audioContext=new AudioContext}else c.canWebcall=!1;var e=function(d){if(d.messageOfTheDay)c.messageOfTheDay=d.messageOfTheDay;if(d.c2cEnabled===!1)c._error("c2cEnabled is false");else if(!d.areAgentsAvailable&&d.isSkillInOpenHours&&!c.options.alwaysShowAgentsAvail||c.options.alwaysShowAgentsUnavail)c._error("areAgentsAvailable is not true (value is "+!(!d.areAgentsAvailable||c.options.alwaysShowAgentsUnavail)+
")");else{var b=d.callableCountries;c.callableCountries={};c.countryCodesInOrder=[];if(b)for(var h=b.length,e=0;e<h;e++){var f=b[e],g=f.country;typeof g=="string"&&(g=g.toUpperCase());f.countryCode=g;c.callableCountries[g]=f;c.countryCodesInOrder.push(g)}if(b=TelephonyUtil.getFromLocalStorage("c2cSavedLastCountry"))b=b.toUpperCase(),b=c.countryCodesInOrder.indexOf(b),b!=-1&&TelephonyUtil.arrayMove(c.countryCodesInOrder,b,0);c.options.showOtherCountryOption&&(c.countryCodesInOrder.push(a.c2c.OTHER_COUNTRY_CODE),
c.callableCountries[a.c2c.OTHER_COUNTRY_CODE]={countryCode:a.c2c.OTHER_COUNTRY_CODE,dialingCode:"",fields:[{minLength:2,maxLength:100}]});if(d.extensionsAllowed===!1)c.options.allowExtension=!1;c.hoursOfOperation=d.hoursOfOperation;c.timeToClosing=d.timeToClosing;b=(b=(b=!d.isSkillInOpenHours)||c.options.alwaysShowOutOfHours)&&!c.options.alwaysShowInHours;c.useVirtualQueue=!1;h=null;if(d.queueTime!==null&&d.queueTime.available)c.useVirtualQueue=!!d.isVirtualQueueEnabled,h=d.queueTime.waitTime;if(d.isWebcallEnabled)c.isWebcallEnabled=
d.isWebcallEnabled;if(d.isWebcallVideoEnabled)c.isWebcallVideoEnabled=d.isWebcallVideoEnabled;c._updateWaitTimeEstimateMessage(h);b?c._setState(c.states.outOfHours):d.isQueueCapExceeded?c._setState(c.states.queueCapExceeded):c._setState(c.states.available)}},g=function(){c._error("Could not get c2c status")};this.options.contextGUID?this._requestCallStatus(function(a){c._setCallStatus(a.callStatusCode);c._isCallInProgress()?(c._updateWaitTimeEstimateMessage(c._isCallWaiting()?a.estimatedWaitTime:
null),c.reattached=!0,c.callStatusPollingEnabled=!0,c._setState(c.states.callInProgress)):c._requestClick2CallStatus(e,g)},function(){c.setContextGUID(null);c.initialize()}):this._requestClick2CallStatus(e,g)};a.c2c.Click2CallWidget.prototype._updateWaitTimeEstimateMessage=function(a){this.waitTimeEstimateMessage=null;if(a!==null){try{a=parseInt(a,10)}catch(e){return}if(a>=0)this.waitTimeEstimateMessage=a<=45E3?this.strings.estimateWait1Min:this.strings.estimateWaitTime.replace(/%s/,Math.ceil((a+
15E3)/6E4))}};a.c2c.Click2CallWidget.prototype._postRenderOutOfHoursState=function(){e(this.container).find(".c2c-hours").amznHoursOfOperationUI({hours:this.hoursOfOperation,strings:this.strings,timezone:this.options.timezone,showTimeZone:this.options.showTimeZone})};a.c2c.Click2CallWidget.prototype._postRenderAvailableState=function(){var c=this;c.options.availableStateCallback();this._populateCountries();this._find(".c2c-country").change(function(){c._updateNumberFormat();c._restorePhoneNumber()});
this._find(".c2c-country").keyup(function(d){if(d.which==a.c2c.key.KEYUP||d.which==a.c2c.key.KEYDOWN||d.which==a.c2c.key.PAGEUP||d.which==a.c2c.key.PAGEDOWN)c._updateNumberFormat(),c._restorePhoneNumber()});this._updateNumberFormat();this._restorePhoneNumber();var f=this._tryPopulateWaitTimeEstimate(".c2c-callme-wait-time-estimate")&&this.useVirtualQueue;(f||this.options.showWhenToCallOptionsAsButtons)&&this._find("div.c2c-form-row-whentocall").hide();f||this._populateWhenToCall();if(this.options.allowExtension){var f=
this._find("input.c2c-extension"),g=this._find("div.c2c-form-row-receptionist");f.val().length>0?g.show():g.hide();this._find("input.c2c-extension").keyup(function(){e(this).val().length>0?c._animateShow(g):g.hide(c.options.receptionistPromptToggleSpeed)});this.options.showExtensionInstructionsOnFocus&&e(this.container).find("input.c2c-extension").focus(function(){c._animateShow(e(c.container).find("div.c2c-extension-instructions"))}).end().find("input.c2c-extension").blur(function(){c._animateHide(e(c.container).find("div.c2c-extension-instructions"))});
this._find("input.c2c-yournumber").focus(function(){c._animateHide(e(c.container).find("div.c2c-errorLine"))});this._find("input.c2c-extension").focus(function(){c._animateHide(e(c.container).find("div.c2c-errorLine"))})}else this._find(".c2c-extension-label").hide().end().find(".c2c-extension").hide();this._find("a.c2c-callme-button").click(function(a){a.preventDefault();c._initiateCall()});c.startingWebcall=!1;this.isWebcallEnabled&&this.canWebcall&&(this._find("a.c2t-call-button").click(function(d){d.preventDefault();
c.startingWebcall=!0;c.videoCallClicked=!1;c._setCallStatus(a.c2c.callStatusCodes.INITIAL);c._setState(c.states.callInProgress)}),this.isWebcallVideoEnabled&&this._find("a.c2t-call-video-button").click(function(d){d.preventDefault();c.startingWebcall=!0;c.videoCallClicked=!0;c._setCallStatus(a.c2c.callStatusCodes.INITIAL);c._setState(c.states.callInProgress)}))};a.c2c.Click2CallWidget.prototype._updateUserErrorStrings=function(){var a=this.strings["userError"+this.userErrorCode+"Header"],e=this.strings["userError"+
this.userErrorCode+"Message"];if(typeof a=="undefined"||typeof e=="undefined")throw"Missing strings for "+this.userErrorCode;e=e.replace(/%s/,'href="#" class="c2c-call-again-link"');this._find("h3.c2c-usererror-header").html(a).end().find("span.c2c-usererror-message").html(e).end()};a.c2c.Click2CallWidget.prototype._updateInProgressStrings=function(){var c,e=!1;this._tryPopulateWaitTimeEstimate(".c2c-inprogress-wait-time-estimate");switch(this.callStatus){case a.c2c.callStatusCodes.INITIAL:case a.c2c.callStatusCodes.DIALING:case a.c2c.callStatusCodes.UNKNOWN:c=
this.startingWebcall?"startWebcall":this.useVirtualQueue?"virtualQueue":"connecting";break;case a.c2c.callStatusCodes.RINGING:c="ringing";break;case a.c2c.callStatusCodes.CONNECTED:c=this.reattached?"connectedAndReattached":"connected";e=!0;break;case a.c2c.callStatusCodes.PENDING:c="pending"}e?(this._find("a.c2c-hangup-button").show(),this._find("a.c2c-cancelcall-button").hide(),this._find("a.c2c-back-button").hide()):(this._find("a.c2c-hangup-button").hide(),this.startingWebcall?(this._find("a.c2c-back-button").show(),
this._find("a.c2c-cancelcall-button").hide()):(this._find("a.c2c-cancelcall-button").show(),this._find("a.c2c-back-button").hide()));var e=this.strings[c+"Header"],g=this.strings[c+"Message"];c=this.strings[c+"Status"];if(this.callStatus==a.c2c.callStatusCodes.PENDING)if(this.callInitiatedTime){var d=(new Date).getTime(),b=Math.max(1,Math.ceil((this.estimatedCallBackTime-d)/6E4));if(b!=1)c=this.strings.pendingStatusPlural;this.log.debug("pending time: now:",d,"estimatedCallBackTime:",this.estimatedCallBackTime);
c=c.replace(/%s/,b)}else c=this.strings.pendingStatusWaitUnknown;this._find("h3.c2c-inprogress-header").html(e).end().find("span.c2c-inprogress-message").html(g).end().find("div.c2c-inprogress-status").find("div.c2c-inprogress-status-message").html(c)};a.c2c.Click2CallWidget.prototype._bindCallAgainLink=function(){var a=this;this._find("a.c2c-call-again-link").click(function(e){a._setState(a.states.initial);a.options.onWidgetResetCallback();e.preventDefault()})};a.c2c.Click2CallWidget.prototype._postRenderUserErrorState=
function(){try{this._updateUserErrorStrings()}catch(a){this._error("Error updating userError state strings: "+a);return}this._bindCallAgainLink()};a.c2c.Click2CallWidget.prototype._postRenderCallEndedState=function(){this._bindCallAgainLink()};a.c2c.Click2CallWidget.prototype.changeWebcallStatus=function(a){this._setCallStatus(a);this._isCallEnded()?this._setState(this.states.callEnded):this._updateInProgressStrings()};a.c2c.Click2CallWidget.prototype._pollCallStatus=function(a){var f=this;f.state==
f.states.callInProgress&&(f.callStatusPollingEnabled?f._requestCallStatus(function(g){f.options.pollCallStatusCallback({isCustomerConnected:f._isCustomerConnected()});f.log.debug("Seq: ",a.sequenceId," Last: ",f.lastCallStatusSequenceId);a.sequenceId==f.lastCallStatusSequenceId&&f.state==f.states.callInProgress&&(e(f.container).find(".c2c-inprogress-update-error").hide(),f._setCallStatus(g.callStatusCode),f.log.debug("call status poll:",f.callStatus),f._isCallEnded()?f._setState(f.states.callEnded):
(f._updateWaitTimeEstimateMessage(f._isCallWaiting()?g.estimatedWaitTime:null),f._updateInProgressStrings(),f._scheduleNextCallStatusPoll()))},function(){if(f.state==f.states.callInProgress){if(a.retriesLeft>0){a.retriesLeft--;var g=Math.pow(f.callStatusPollDelay/1E3,f.callStatusRetriesBeforeGivingUp-a.retriesLeft-1)*1E3;f.log.debug("did not get status, retries before giving up:",a.retriesLeft,"backoff ms:",g);f._scheduleNextCallStatusPoll(a,g)}a.retriesLeft==f.callStatusRetriesBeforeError&&(e(f.container).find(".c2c-successLine").hide(),
e(f.container).find(".c2c-inprogress-status").hide(),e(f.container).find(".c2c-inprogress-update-error").show());return!0}}):f._scheduleNextCallStatusPoll())};a.c2c.Click2CallWidget.prototype._scheduleNextCallStatusPoll=function(a,e){typeof e=="undefined"&&(e=0);if(typeof this.lastCallStatusSequenceId=="undefined")this.lastCallStatusSequenceId=0;typeof a=="undefined"&&(a={retriesLeft:this.callStatusRetriesBeforeGivingUp});a.sequenceId=++this.lastCallStatusSequenceId;var g=this.callStatusPollDelay;
e>0&&(g+=e);var d=this;window.setTimeout(function(){d._pollCallStatus(a)},g)};a.c2c.Click2CallWidget.prototype._postRenderCallInProgressState=function(){this._updateInProgressStrings();var c=this;c.startingWebcall?(c._find("a.c2c-back-button").unbind("click").click(function(a){c.changeWebcallStatus(c.states.callEnded);a.preventDefault()}),c._find("div.webcall-container").show(),(new a.c2c.SipmlAdapter(c)).initSipmlWebcall()):(c._find("div.webcall-container").hide(),c._find("a.c2c-hangup-button, a.c2c-cancelcall-button").unbind("click").click(function(a){c._disconnectCall();
a.preventDefault()}),c._scheduleNextCallStatusPoll())};a.c2c.Click2CallWidget.prototype._setStateClass=function(a){for(var f in this.states)f==a?e(this.container).addClass("c2c-state-"+f):e(this.container).removeClass("c2c-state-"+f)};a.c2c.Click2CallWidget.prototype._setState=function(a){this.state=a;this.renderTemplate();switch(a){case this.states.initial:this._postRenderInitialState();break;case this.states.available:this._postRenderAvailableState();break;case this.states.outOfHours:this._postRenderOutOfHoursState();
break;case this.states.callInProgress:this._postRenderCallInProgressState();break;case this.states.callEnded:this.setContextGUID(null);this._postRenderCallEndedState();break;case this.states.userError:this.setContextGUID(null);this._postRenderUserErrorState();break;case this.states.notAvailable:case this.states.queueCapExceeded:this.setContextGUID(null)}typeof this.options.stateChangeCallback=="function"&&(this.options.stateChangeCallback(a.id),this._raiseEvent("StateChange",{state:a.id}))};a.c2c.Click2CallWidget.prototype.renderTemplate=
function(){var a=this.state.template,f=this.options.messageOfTheDay||this.messageOfTheDay;f&&(a+=this.options.messageOfTheDayTemplate.replace(/%s/,f));this.state===this.states.available&&this.isWebcallEnabled&&this.canWebcall&&(a+="<h4>"+this.strings.availableC2THeader+"</h4><p>"+this.strings.availableC2TInstructions+'</p><div class="c2t-form-row"><span class="c2c-callme-button-spacer"></span><a href="#" class="c2t-call-button">'+this.strings.click2TalkButton+"</a>",this.isWebcallVideoEnabled&&(a+=
'&nbsp;&nbsp<a href="#" class="c2t-call-video-button">'+this.strings.click2TalkVideoButton+"</a>"),a+="</div>");e(this.container).get(0).innerHTML=a;this._setStateClass(this.state.id);this.options.showDebugSection&&this._renderDebugSection()};a.c2c.Click2CallWidget.prototype._renderDebugSection=function(){e("<div class='cs-c2c-debug-section'>").css({border:"1px #aaa solid",margin:"5px",padding:"5px"}).append(e("<div>").text("c2cId: "+this.options.c2cId)).appendTo(this.container)};e.fn.amazonClick2Call=
function(c){return this.each(function(){var f=new a.c2c.Click2CallWidget(this,c);e(this).addClass("c2c-container");f.initialize()})}})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.c2c=="undefined")a.c2c={};var c={Monday:0,Tuesday:1,Wednesday:2,Thursday:3,Friday:4,Saturday:5,Sunday:6};e.fn.amznHoursOfOperationUI=function(c){return this.each(function(){new a.c2c.HoursOfOperationUI(this,c)})};a.c2c.HoursOfOperationUI=function(a,c){this.options=e.extend({timezone:"America/Los_Angeles",showTimeZone:!0,
hours:[]},c);this.strings=e.extend({openAllDayHours:"Open all day",dayRangeDelimiter:"-",dayRangeTerminator:":",hourRangeDelimiter:" - ",hourRangeListDelimiter:", ",am:"AM",pm:"PM",midnight:"Midnight",noon:"Noon",everyDayOfTheWeek:"Every day of the week",dayNameMonday:"Monday",dayNameTuesday:"Tuesday",dayNameWednesday:"Wednesday",dayNameThursday:"Thursday",dayNameFriday:"Friday",dayNameSaturday:"Saturday",dayNameSunday:"Sunday","tzNameAmerica/Los_Angeles":"Pacific","tzNameEurope/London":"London",
"tzNameEurope/Paris":"Paris","tzNameEurope/Berlin":"Berlin","tzNameAsia/Tokyo":"Tokyo"},c.strings);this._render(a)};a.c2c.HoursOfOperationUI.prototype._render=function(a){var c=this._collapseDailyHours(this.options.hours);e(a).empty();for(var d=0;d<c.length;d++){var b=c[d].startDay,h=c[d].endDay,i=c[d].hours;e(a).append('<div class="c2c-hours-row"><span class="c2c-day-range">'+this._formatDayRange(b,h)+'</span><span class="c2c-hour-range">'+this._formatHours(i)+"</span></div>")}};a.c2c.HoursOfOperationUI.prototype._areHoursEqual=
function(a,c){if(a.length!=c.length)return!1;for(var d=0;d<a.length;d++){if(a[d].startHour!=c[d].startHour)return!1;if(a[d].endHour!=c[d].endHour)return!1}return!0};a.c2c.HoursOfOperationUI.prototype._collapseDailyHours=function(a){a.sort(function(a,b){return c[a.dayName]-c[b.dayName]});for(var e=[],d;d=a.shift();){var b=e[e.length-1],h=1;b&&(h=c[d.dayName]-c[b.endDay||b.startDay]);b&&h==1&&this._areHoursEqual(b.hours,d.operationTimeSlices)?b.endDay=d.dayName:e.push({startDay:d.dayName,endDay:null,
hours:d.operationTimeSlices})}return e};a.c2c.HoursOfOperationUI.prototype._formatHour=function(a,c){return c==="0000"&&this.strings.midnight?this.strings.midnight:c==="1200"&&this.strings.noon?this.strings.noon:a.replace(/AM/,this.strings.am).replace(/PM/,this.strings.pm)};a.c2c.HoursOfOperationUI.prototype._formatHours=function(a){for(var c=[],d=!1,b=0;b<a.length;b++){var h=a[b].startHour,i=a[b].endHour,m=a[b].startHourRaw,u=a[b].endHourRaw;typeof h=="string"&&h===i?(c.push(this.strings.openAllDayHours),
d=!0):(h=this._formatHour(h,m),i=this._formatHour(i,u),c.push(h+this.strings.hourRangeDelimiter+i))}!d&&c&&(c[c.length-1]+=this._formatTimeZone(this.options.timezone));var l=this,c=e.map(c,function(a,b){var d=a;b<c.length-1&&(d+=l.strings.hourRangeListDelimiter);return'<span class="c2c-hour-range-line">'+d+"</span>"});return c.join("")};a.c2c.HoursOfOperationUI.prototype._formatDayRange=function(a,e){var d;c[a]===0&&c[e]===6&&this.strings.everyDayOfTheWeek?d=this.strings.everyDayOfTheWeek:(d=this.strings["dayName"+
a],e&&(d+=this.strings.dayRangeDelimiter+this.strings["dayName"+e]));return d+this.strings.dayRangeTerminator};a.c2c.HoursOfOperationUI.prototype._formatTimeZone=function(a){a=this.strings["tzName"+a];return this.options.showTimeZone&&a?" ("+a+")":""}})(j);(function(a){var c=function(){var a=document.createElement("input");a.setAttribute("onpaste","");return typeof a.onpaste==="function"?"paste":"input"}()+".mask",f=navigator.userAgent,g=/iphone/i.test(f),d=/android/i.test(f),b;a.mask={definitions:{9:"[0-9]",
a:"[A-Za-z]","*":"[A-Za-z0-9]"},dataName:"rawMaskFn",placeholder:"_"};a.fn.extend({caret:function(a,b){var d;if(!(this.length===0||this.is(":hidden")))return typeof a=="number"?(b=typeof b==="number"?b:a,this.each(function(){this.setSelectionRange?this.setSelectionRange(a,b):this.createTextRange&&(d=this.createTextRange(),d.collapse(!0),d.moveEnd("character",b),d.moveStart("character",a),d.select())})):(this[0].setSelectionRange?(a=this[0].selectionStart,b=this[0].selectionEnd):document.selection&&
document.selection.createRange&&(d=document.selection.createRange(),a=0-d.duplicate().moveStart("character",-1E5),b=a+d.text.length),{begin:a,end:b})},unmask:function(){return this.trigger("unmask")},mask:function(h,i){var f,u,l,k,n,j;if(!h&&this.length>0)return f=a(this[0]),f.data(a.mask.dataName)();i=a.extend({placeholder:a.mask.placeholder,completed:null},i);u=a.mask.definitions;l=[];k=j=h.length;n=null;a.each(h.split(""),function(a,b){b=="?"?(j--,k=a):u[b]?(l.push(RegExp(u[b])),n===null&&(n=l.length-
1)):l.push(null)});return this.trigger("unmask").each(function(){function f(a){for(;++a<j&&!l[a];);return a}function m(a,b){var d,h;if(!(a<0)){for(d=a,h=f(b);d<j;d++)if(l[d]){if(h<j&&l[d].test(y[h]))y[d]=y[h],y[h]=i.placeholder;else break;h=f(h)}w();t.caret(Math.max(n,a))}}function o(a){var b=a.which,d,h;if(b===8||b===46||g&&b===127){d=t.caret();h=d.begin;d=d.end;if(d-h===0){if(b!==46)for(;--h>=0&&!l[h];);else h=d=f(h-1);d=b===46?f(d):d}z(h,d);m(h,d-1);a.preventDefault()}else b==27&&(t.val(A),t.caret(0,
x()),a.preventDefault())}function s(b){var h=b.which,c=t.caret();if(!b.ctrlKey&&!b.altKey&&!(b.metaKey||h<32)&&h){c.end-c.begin!==0&&(z(c.begin,c.end),m(c.begin,c.end-1));c=f(c.begin-1);if(c<j&&(h=String.fromCharCode(h),l[c].test(h))){var o,s,g,k;for(o=c,s=i.placeholder;o<j;o++)if(l[o])if(g=f(o),k=y[o],y[o]=s,g<j&&l[g].test(k))s=k;else break;y[c]=h;w();c=f(c);d?setTimeout(a.proxy(a.fn.caret,t,c),0):t.caret(c);i.completed&&c>=j&&i.completed.call(t)}b.preventDefault()}}function z(a,b){var d;for(d=a;d<
b&&d<j;d++)if(l[d])y[d]=i.placeholder}function w(){t.val(y.join(""))}function x(a){var b=t.val(),d=-1,h,c;for(h=0,pos=0;h<j;h++)if(l[h]){for(y[h]=i.placeholder;pos++<b.length;)if(c=b.charAt(pos-1),l[h].test(c)){y[h]=c;d=h;break}if(pos>b.length)break}else y[h]===b.charAt(pos)&&h!==k&&(pos++,d=h);a?w():d+1<k?(t.val(""),z(0,j)):(w(),t.val(t.val().substring(0,d+1)));return k?h:n}var t=a(this),y=a.map(h.split(""),function(a){if(a!="?")return u[a]?i.placeholder:a}),A=t.val();t.data(a.mask.dataName,function(){return a.map(y,
function(a,b){return l[b]&&a!=i.placeholder?a:null}).join("")});t.attr("readonly")||t.one("unmask",function(){t.unbind(".mask").removeData(a.mask.dataName)}).bind("focus.mask",function(){clearTimeout(b);var a;A=t.val();a=x(!0);b=setTimeout(function(){w();a==h.length?t.caret(0,a):t.caret(a)},10)}).bind("blur.mask",function(){x(!0);t.val()!=A&&t.change()}).bind("keydown.mask",o).bind("keypress.mask",s).bind(c,function(){setTimeout(function(){var a=x(!0);t.caret(a);i.completed&&a==t.val().length&&i.completed.call(t)},
0)});x()})}})})(j);(function(e){typeof a=="undefined"&&(a={});if(typeof a.c2c=="undefined")a.c2c={};var c=document.createElement("input");c.setAttribute("type","tel");var f=c.type!=="text"?"tel":"text";a.c2c.PhoneNumberField=function(c,d){this.c2cWidget=d;if(c){this.minDigits=c.minLength;this.maxDigits=c.maxLength;var b=d._getCurrentCountry(),h=document.createElement("input");h.id="c2c-yournumber-"+d.getInstanceId();h.className="c2c-yournumber";h.type=f;if(this.enforcesMaxDigits())h.maxLength=this.maxDigits;
b===a.c2c.OTHER_COUNTRY_CODE?e(h).addClass("c2c-yournumber-othercountry"):(b=Math.min(this.maxDigits,12),h.style.width=b+"em");h.title=d.getString("yourNumberTip");var i=this;h.getFieldObject=function(){return i};this.domElem=h}};a.c2c.PhoneNumberField.prototype.getDomElement=function(){return this.domElem};a.c2c.PhoneNumberField.prototype.getValue=function(){return this.domElem.value};a.c2c.PhoneNumberField.prototype.getMinDigits=function(){return this.minDigits};a.c2c.PhoneNumberField.prototype.getMaxDigits=
function(){return this.maxDigits};a.c2c.DividedPhoneNumberField=function(c,d){this.constructor=a.c2c.DividedPhoneNumberField;a.c2c.PhoneNumberField.call(this,c,d)};a.c2c.DividedPhoneNumberField.prototype=new a.c2c.PhoneNumberField;a.c2c.DividedPhoneNumberField.prototype.enforcesMaxDigits=function(){return!0};a.c2c.DividedPhoneNumberField.prototype.validate=function(){var c=[];this.getValue().match(/^\d*$/)||c.push(new a.c2c.InvalidCharsValidationError(this,this.c2cWidget));this.getValue().length<
this.minDigits&&c.push(new a.c2c.TooShortValidationError(this,this.c2cWidget));return c};a.c2c.SinglePhoneNumberField=function(c,d){this.constructor=a.c2c.SinglePhoneNumberField;a.c2c.PhoneNumberField.call(this,c,d);var b=d._getCurrentCountryConfig().countryCode;this.stripLeadingZeros=a.c2c.leadingZeroPrefixCountries[b]?!1:!0;e(this.getDomElement()).addClass("c2c-yournumber-singlefield")};a.c2c.SinglePhoneNumberField.prototype=new a.c2c.PhoneNumberField;a.c2c.SinglePhoneNumberField.prototype.enforcesMaxDigits=
function(){return!1};a.c2c.SinglePhoneNumberField.prototype.getValue=function(){var a=this.domElem.value.replace(/[^\d]/g,"");this.stripLeadingZeros&&(a=a.replace(/^0+/,""));return a};a.c2c.SinglePhoneNumberField.prototype.validate=function(){var c=[];this.getValue().length<this.minDigits&&c.push(new a.c2c.TooShortValidationError(this,this.c2cWidget));this.getValue().length>this.maxDigits&&c.push(new a.c2c.TooLongValidationError(this,this.c2cWidget));return c};a.c2c.ValidationError=function(a,d){this.message=
d;this.fieldInError=a};a.c2c.ValidationError.prototype.getMessage=function(){return this.message};a.c2c.ValidationError.prototype.getFieldInError=function(){return this.fieldInError};a.c2c.TooLongValidationError=function(c,d){this.constructor=a.c2c.TooLongValidationError;a.c2c.ValidationError.call(this,c,d.getString("tooLongError").replace(/%s/,c.getMaxDigits()))};a.c2c.TooLongValidationError.prototype=new a.c2c.ValidationError;a.c2c.TooShortValidationError=function(c,d){this.constructor=a.c2c.TooShortValidationError;
a.c2c.ValidationError.call(this,c,d.getString("tooShortError").replace(/%s/,c.getMinDigits()))};a.c2c.TooShortValidationError.prototype=new a.c2c.ValidationError;a.c2c.InvalidCharsValidationError=function(c,d){this.constructor=a.c2c.InvalidCharsValidationError;a.c2c.ValidationError.call(this,c,d.getString("invalidCharsError"))};a.c2c.InvalidCharsValidationError.prototype=new a.c2c.ValidationError})(j);(function(){typeof a=="undefined"&&(a={});if(typeof a.tel=="undefined")a.tel={};if(typeof a.tel.retry==
"undefined")a.tel.retry={};a.tel.retry.doTaskWithRetries=function(e){var c=e.task,f=e.maxRetries,g=e.retryDelay||2E3,d=e.backoff||"constant",b=e.retryTimeLimit,h=e.onFail||function(){},i=e.onSuccess||function(){},m=e.onGiveUp||function(){};if(typeof f=="undefined"||f==null&&!b)f=3;var u=a.tel.retry.backoffFuncs[d],l=0,k=(new Date).getTime(),n=function(a,d){typeof d!="undefined"&&(g=d);if(a)return i();else{var e=!!b&&(new Date).getTime()-k>b,o=f!==null&&l>=f;l++;h(l);if(o||e)return m();else e=g+u(l,
g),window.setTimeout(function(){c(n,l)},e)}};return c(n,l)};a.tel.retry.backoffFuncs={exponential:function(a,c){return Math.pow(c,a)-c},linear:function(a,c){return(a-1)*c},constant:function(a,c){return c}}})()};window.P&&window.P.AUI_BUILD_DATE?P.when("jQuery","TelephonyJSLogger").execute(function(j){p(j);P.register("TelephonyC2CCommon",function(){})}):p(window.jQuery)})();